# Generated by Django 5.2.4 on 2025-07-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='nos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Seat'),
        ),
        migrations.AddField(
            model_name='train',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='class_type',
            field=models.ManyToManyField(blank=True, null=True, to='app.classtype'),
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='To+', to='app.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Train Name'),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='From+', to='app.station'),
        ),
    ]
