# Generated by Django 5.2.4 on 2025-07-23 07:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_train_arrival_time_train_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactnumber',
            old_name='number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='booking_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='classtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='classtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='emergency_center',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Center Phone Number'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='help_desk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help Desk Phone Number'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.station'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='station_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Station Phone Number'),
        ),
        migrations.AddField(
            model_name='contactnumber',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 7, 36, 28, 405196, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(auto_created=True, blank=True, default='Paid', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='adult',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='child',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='class_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='fpp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Fare Per Passenger'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='nop',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Passengers'),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='total_fare',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='train',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='travel_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetail',
            name='travel_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='class_type',
            field=models.ManyToManyField(blank=True, to='app.classtype'),
        ),
    ]
