# Generated by Django 5.2.4 on 2025-07-23 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_number_contactnumber_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 8, 18, 38, 403027, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='station',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
