# Generated by Django 5.2.4 on 2025-07-23 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_station_code_station_created_at_station_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.classtype'),
        ),
    ]
