# Generated by Django 5.2.4 on 2025-07-28 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_train_options_alter_train_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
